=== tmforum-rand/TMForum-ODA-Asset-Build/components/TMFC029-paymentManagement/component-ctk/resources/api-ctks/TMF670-PaymentMethod/ctk/schemas/PaymentMethod-DirectDebit.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "@type": {
      "type": "string"
    },
    "mandateId": {
      "type": "string"
    },
    "mandateType": {
      "type": "string"
    },
    "accountNumber": {
      "type": "string"
    },
    "firstDebitDate": {
      "type": "string"
    },
    "lastDebitDate": {
      "type": "string"
    },
    "owner": {
      "type": "string"
    },
    "bank": {
      "type": "string"
    }
  },
  "required": [
    "@type",
    "accountNumber",
    "bank",
    "firstDebitDate",
    "lastDebitDate",
    "mandateId",
    "mandateType",
    "name",
    "owner"
  ]
}

=== tmforum-rand/TMForum-ODA-Asset-Build/components/TMFC029-paymentManagement/component-ctk/resources/api-ctks/TMF670-PaymentMethod/ctk/schemas/PaymentMethod-DirectDebit.example.json
{
    "name": "debit",
    "@type": "DirectDebit",
    "mandateId": "123",
    "mandateType": "single",
    "accountNumber": "AL47 2121 1009 0000 0002 3569 87411",
    "firstDebitDate": "2021-11-12T17:42:04.317Z",
    "lastDebitDate": "2021-11-12T17:42:04.317Z",
    "owner": "Entity",
    "bank" : "HSBC"
}
