=== tmforum-rand/TMForum-ODA-Asset-Build/components/TMFC020-agreementManagement/component-ctk/resources/api-ctks/TMF651-Agreement/ctk/schemas/Agreement.schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "agreementType": {
            "type": "string"
        },
        "agreementItem": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "termOrCondition": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "id": {
                                    "type": "string"
                                },
                                "validFor": {
                                    "type": "object",
                                    "properties": {
                                        "startDateTime": {
                                            "type": "string"
                                        },
                                        "endDateTime": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "endDateTime",
                                        "startDateTime"
                                    ]
                                }
                            },
                            "required": [
                                "description",
                                "id",
                                "validFor"
                            ]
                        }
                    }
                },
                "required": [
                    "termOrCondition"
                ]
            }
        },
        "engagedPartyRole": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "@referredType": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "role": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "@referredType",
                    "id",
                    "name",
                    "role"
                ]
            }
        }
    },
    "required": [
        "agreementItem",
        "agreementType",
        "engagedPartyRole",
        "name"
    ]
}

=== tmforum-rand/TMForum-ODA-Asset-Build/components/TMFC020-agreementManagement/component-ctk/resources/api-ctks/TMF651-Agreement/ctk/schemas/Agreement.example.json
{
    "name": "Summer Contract Agreement", 
    "agreementType": "commercial", 
    "agreementItem": [
        {
           
            "termOrCondition": [
                {
                    "description": "This  agreement term or condition ...", 
                    "id": "5890", 
                    "validFor": {
                        "startDateTime": "2018-04-25T00:00:00.000Z", 
                        "endDateTime": "2018-11-20T00:00:00.000Z"
                    }
                }
            ]
        }
    ], 
    "engagedPartyRole": [
        {
            "@referredType": "Organization",
            "id": "330", 
            "role": "Supplier", 
            "name": "Magic Tools Company"
        }
    ]
}
