=== tmforum-rand/TMForum-ODA-Asset-Build/components/TMFC020-digitalIdentityManagement/component-ctk/resources/api-ctks/TMF720-DigitalIdentity/ctk/schemas/DigitalIdentity.schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "credential": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "@type": {
                        "type": "string"
                    }
                },
                "required": [
                    "@type",
                    "id"
                ]
            }
        },
        "individualIdentified": {
            "type": "object",
            "properties": {
                "@referredType": {
                    "type": "string"
                },
                "@type": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            },
            "required": [
                "@referredType",
                "@type",
                "id"
            ]
        },
        "partyRoleIdentified": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "@referredType": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "role": {
                        "type": "string"
                    }
                },
                "required": [
                    "@referredType",
                    "id"
                ],
                "if": {
                    "properties": {
                        "@referredType": { "const": "Party"} 
                    }
                },
                "then": {
                    "required": ["role"]
                }
            }
        },
        "resourceIdentified": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            },
            "required": [
                "id"
            ]
        }
    },
    "required": [
        "credential"
    ],
    "oneOf": [
        {"required": ["resourceIdentified"]},
        {"required": ["partyRoleIdentified"]},
        {"required": ["individualIdentified"]}
    ]
}

=== tmforum-rand/TMForum-ODA-Asset-Build/components/TMFC020-digitalIdentityManagement/component-ctk/resources/api-ctks/TMF720-DigitalIdentity/ctk/schemas/DigitalIdentity.example.json
{
    "credential": [{
        "id": "caf79e81-c3c2-48bd-94f4-62028fa22a1f",
        "@type": "Credential"
    }],
    "individualIdentified": {
        "@referredType": "Individual",
        "@type": "IndividualIdentified",
        "id": "1f197c10-6a6a-452e-9a05-fe0ccb2c0d79"
    },
    "partyRoleIdentified": [{
        "@referredType": "Party",
        "id": "2ff80fb3-742f-4acf-ba80-ea787ebb4a05",
        "role": "individual"
    }],
    "resourceIdentified": {
        "id": "d09b984f-4033-4ccd-b2d7-6ecf83341107"
    }
}
